name: Build and Push Docker Images on Tag

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }} ./workspaces/backend

      - name: Push backend Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/backend:${{ github.ref_name }}

  build-and-push-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build frontend Docker image
        run: |
          docker build --build-arg BACKEND_API_ORIGIN=http://backend:3001 -t ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }} ./workspaces/frontend

      - name: Push frontend Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/frontend:${{ github.ref_name }}
